version: '3.9'
name: Warehouse

services:
   backend:
      build: .
      container_name: springboot-app
      env_file:
      - .env
      ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      depends_on:
         app-db:
            condition: service_healthy
         mailhog:
            condition: service_started
      networks:
      - ipv4

   app-db:
      image: postgres:17
      container_name: postgresql
      environment:
         POSTGRES_USER: ${DB_USERNAME}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}
      ports:
          - 5432:5432
      volumes:
      - warehousedb_data:/var/lib/postgresql/data
      healthcheck:
         test:
         - CMD-SHELL
         - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
         interval: 10s
         timeout: 5s
         retries: 5

      networks:
      - ipv4
   mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
      - ${MAIL_PORT}:1025
      - ${MAIL_UI}:8025

      networks:
      - ipv4

volumes:
   warehousedb_data: null
networks:
   ipv4:
      driver: bridge