name: Warehouse build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (cache maven)
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build & test (unit + IT)
        run: mvn -B -U clean verify

      - name: Build image with Maven profile
        run: mvn -B -DskipTests -P docker package

      - name: Health check
        run: |
          docker compose up -d
          sleep 100
          curl -f http://localhost:6565/api/health

      - name: Stop compose
        if: always()
        run: docker compose down -v

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}